server:
  port: 9898

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
    password: postgres
    username: postgres
    database:
      host: localhost
      port: 5432
      name: auth_service

  application:
    name: IDENTITY-SERVICE

  jpa:
    hibernate:
      ddl-auto: create

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true