server:
  port: 9999

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${spring.datasource.database.host}:${spring.datasource.database.port}/${spring.datasource.database.name}
    password: postgres
    username: postgres
    database:
      host: localhost
      port: 5000
      name: identity_service

  application:
    name: IDENTITY-SERVICE

  jpa:
    hibernate:
      ddl-auto: create

eureka-hostname: localhost

eureka:
  client:
    service-url:
      defaultZone : http://${eureka-hostname}:8761/eureka/