version: "3.8"

services:
  api-gateway:
    depends_on:
    - eureka-server
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  identity-service:
    depends_on:
    - eureka-server
    build:
      context: ./identity-service
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATASOURCE_DATABASE_HOST=postgres-identity-service
      - SPRING_DATASOURCE_DATABASE_PORT=5000
      - SPRING_DATASOURCE_DATABASE_NAME=identity_service

  housing-category-service:
    depends_on:
    - eureka-server
    build:
      context: ./housing-category-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka-server:
    depends_on:
    - postgres-identity-service
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  postgres-identity-service:
    restart: always
    image: postgres:14.8-alpine3.18
    container_name: airbnb_identity_service_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: identity_service
    ports:
      - "5000:5000"
    command: -p 5000
    volumes:
      - ./postgres-data-identity-service:/var/lib/postgresql/data