version: "3.8"

services:
  postgres-auth-service:
    restart: always
    image: postgres:14.8-alpine3.18
    container_name: airbnb_auth_service_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_service
    ports:
      - "5432:5432"
      - "5435:5432"
    volumes:
      - ./postgres-data-auth-service:/var/lib/postgresql/data