server:
  port: 9002

spring:
  application:
    name: HOUSING-CATEGORY-SERVICE

eureka-hostname: localhost

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-hostname}:8761/eureka/
