name: Eureka server docker build

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:services/eureka-server"
          push: true
          tags: ghcr.io/ap1kkk/airbnb-eureka-server:latest
        env:
          REPO_USERNAME: ${{ github.actor }}
          REPO_PASSWORD: ${{ secrets.GITHUB_TOKEN }}