name: Housing category service docker build

on:
  push:
    branches:
      - main
#    paths:
#      - "**/services/housing-category-service/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission for gradlew
        working-directory: ./services/housing-category-service
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: ./services/housing-category-service
        run: ./gradlew build --no-daemon --build-cache -i
        env:
          REPO_USERNAME: ${{ github.actor }}
          REPO_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Check current dir
        run: ls -a ./services/housing-category-service

      - name: Increment version
        id: increment_version
        run: |
          echo "Fetching current version..."
          current_version=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/HOUSING_CATEGORY_IMAGE_VERSION \
            | jq -r '.value')
          echo "Current version: $current_version"
          
          # Increment the version (this assumes semantic versioning)
          IFS='.' read -r -a version_parts <<< "$current_version"
          ((version_parts[2]++))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "New version: $new_version"
          
          # Update the repository variable
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables/HOUSING_CATEGORY_IMAGE_VERSION \
            -d "{\"name\":\"HOUSING_CATEGORY_IMAGE_VERSION\",\"value\":\"$new_version\"}"
          
          echo "version=$new_version" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./services/housing-category-service
          push: true
          tags: ghcr.io/ap1kkk/airbnb-housing-category-service::${{ env.version }}