name: Housing category service docker build

on:
  push:
    paths:
      - "**/services/housing-category-service/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Grant execute permission for gradlew
        run: chmod +x ./services/gradlew

      - name: Build with Gradle
        run: ./services/gradlew --no-daemon --build-cache :housing-category-service:build
        env:
          REPO_USERNAME: ${{ github.actor }}
          REPO_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:services/housing-category-service"
          push: true
          tags: ghcr.io/ap1kkk/airbnb-housing-category-service:latest